language: android
android:
  components:
    - build-tools-22.0.1
    - android-22  
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository	
before_script:
  - chmod +x gradlew
script: ./gradlew clean assemble
notifications:
  email: false 